export const personalData = {
  Vegetables: [
    {
      id: 1,
      name: "Mushrooms",
      description: "8 oz",
      price: 2.47,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/163/460/6000202163460.jpg",
      ratings: 4,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      name: "Cucumber",
      id: 2,
      description: "Sold in singles",
      price: 1.67,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/094/566/6000200094566.jpg",
      ratings: 4.5,
      isFavorite: true,
      hasOffer: false,
      isAddedToCart: true,
      quantity: 0,
    },
    {
      id: 3,
      name: "Tomato",
      description: "Sold in singles",
      price: 0.62,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/lu4/853/999999-PLU4853.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: true,
      isAddedToCart: true,
      quantity: 0,
    },
    {
      id: 4,
      name: "Ginger",
      description: "Sold in singles",
      price: 0.75,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/271/867/6000191271867.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: true,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 5,
      name: "Cabbage",
      description: "Sold in singles",
      price: 6.75,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/272/109/6000191272109.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 6,
      name: "Cauliflower",
      description: "Sold in singles",
      price: 3.97,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/272/324/6000191272324.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: false,
      isAddedToCart: true,
      quantity: 0,
    },
    {
      id: 7,
      name: "Potato",
      description: "5 lb",
      price: 5.75,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/653/750/6000198653750.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 8,
      name: "Onion",
      description: "3 lb Bag",
      price: 3.5,
      type: "vegetables",
      url: "https://i5.walmartimages.ca/images/Thumbnails/282/958/6000191282958.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 9,
      name: "Banana",
      description: "Sold in singles",
      price: 0.47,
      type: "fruits",
      url: "https://i5.walmartimages.ca/images/Thumbnails/580/6_r/875806_R.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 10,
      name: "Apple",
      description: "single count",
      price: 0.59,
      type: "fruits",
      url: "https://i5.walmartimages.ca/images/Thumbnails/094/514/6000200094514.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: true,
      isAddedToCart: true,
      quantity: 0,
    },
    {
      id: 11,
      name: "Grapefruit",
      description: "Sold in singles",
      price: 1.59,
      type: "fruits",
      url: "https://i5.walmartimages.ca/images/Thumbnails/478/2_r/6000195944782_R.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: true,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 12,
      name: "Blackberries",
      description: "6 oz",
      price: 3.59,
      type: "fruits",
      url: "https://i5.walmartimages.ca/images/Thumbnails/561/109/6000198561109.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 13,
      name: "Dragon Fruit",
      description: "Sold in singles",
      price: 3.88,
      type: "fruits",
      url: "https://i5.walmartimages.ca/images/Thumbnails/094/493/6000200094493.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 14,
      name: "Kiwi",
      description: "Sold in singles",
      price: 0.87,
      type: "fruits",
      url: "https://i5.walmartimages.ca/images/Thumbnails/094/500/6000200094500.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 15,
      name: "Rosemary",
      description: "7 g tray",
      price: 0.87,
      type: "herbs",
      url: "https://i5.walmartimages.ca/images/Thumbnails/507/980/625280507980.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 16,
      name: "Parsley",
      description: "Sold in bunches",
      price: 1.87,
      type: "herbs",
      url: "https://i5.walmartimages.ca/images/Thumbnails/094/551/6000200094551.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 17,
      name: "Mint",
      description: "Sold in bunches",
      price: 0.67,
      type: "herbs",
      url: "https://i5.walmartimages.ca/images/Thumbnails/801/072/999999-625647801072.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 18,
      name: "Curry Leaves",
      description: "3.5 oz",
      price: 1.97,
      type: "herbs",
      url: "https://i5.walmartimages.ca/images/Thumbnails/020/798/6000200020798.jpg",
      ratings: 3,
      isFavorite: true,
      hasOffer: false,
      isAddedToCart: true,
      quantity: 0,
    },
    {
      id: 19,
      name: "Fresh Attitude Spring Mix Salad Kit",
      description: "5.3 oz",
      price: 5.97,
      type: "salade",
      url: "https://i5.walmartimages.ca/images/Thumbnails/469/9_r/10294699_R.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 20,
      name: "Fresh Attitude Caesar Salad Kit",
      description: "6 oz",
      price: 6.97,
      type: "salade",
      url: "https://i5.walmartimages.ca/images/Thumbnails/459/4_r/10294594_R.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
  ],
  Fruits: [
    {
      id: 21,
      name: "Yogurt",
      description: "750 g",
      price: 2.77,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/891/145/6000202891145.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 22,
      name: "Eggs",
      description: "12 Count",
      price: 3.07,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/924/227/6000197924227.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 23,
      name: "Cheddar Cheese",
      description: "400 g",
      price: 5.07,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/014/470/627735014470.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 24,
      name: "Sealtest Partly Skimmed 2% Milk",
      description: "4 L bag",
      price: 4.68,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/487/617/6000201487617.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 25,
      name: "Natrel Fine-filtered 2 %  Milk",
      description: "4 L",
      price: 4.64,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/514/354/6000202514354.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 26,
      name: "Mozarella Marble Cheestrings",
      description: "16 Pack",
      price: 5.9,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/4_m/ain/999999-6820085824_Main.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 27,
      name: "Paneer",
      description: "375 g",
      price: 5.9,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/820/052/6000202820052.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 28,
      name: "Brown Eggs",
      description: "18 Count",
      price: 5.94,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/343/114/999999-999999-64767343114.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 29,
      name: "Becel Margarine Original",
      description: "907g",
      price: 5.97,
      type: "dairy",
      url: "https://i5.walmartimages.ca/images/Thumbnails/293/228/6000201293228.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
  ],
  Meat: [
    {
      id: 30,
      name: "Boneless Smoked Ham",
      description: "GV boneless smoked ham",
      price: 12,
      type: "meat",
      url: "https://i5.walmartimages.ca/images/Thumbnails/934/467/6000200934467.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 31,
      name: "Original Wieners",
      description: "24 wieners, 900 g",
      price: 5,
      type: "meat",
      url: "https://i5.walmartimages.ca/images/Thumbnails/020/808/627735020808.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 32,
      name: "Mild Italian Sausages",
      description: "375 g",
      price: 5.99,
      type: "meat",
      url: "https://product-images.metro.ca/images/h73/h60/10053801312286.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 33,
      name: "Maple Leaf Original Natural Bacon",
      description: "375 g",
      price: 6.99,
      type: "meat",
      url: "https://i5.walmartimages.ca/images/Thumbnails/219/406/999999-63100219406.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 34,
      name: "AAA Angus Boneless Blade Steak, Your Fresh Market",
      description: "2-3 pieces per tray",
      price: 16.99,
      type: "meat",
      url: "https://i5.walmartimages.ca/images/Thumbnails/204/846/6000200204846.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
  ],
  Personal: [
    {
      id: 36,
      name: "Heinz Tomato Ketchup",
      description: "1L",
      price: 4.27,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/_96/457/96457.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 37,
      name: "HERSHEY'S CHIPITS Milk Chocolate Baking Chips",
      description: "270g",
      price: 3.77,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/_93/984/93984.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 38,
      name: "Kraft Smooth Peanut Butter",
      description: "1kg",
      price: 5.47,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/184/943/184943.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 39,
      name: "Mr. Noodles Chicken Flavour Instant Noodles",
      description: "85g",
      price: 0.47,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/115/404/115404.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 40,
      name: "Redpath Special Fine Granulated Sugar",
      description: "2 kg",
      price: 2.47,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/866/444/866444.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 41,
      name: " Pure White Vinegar",
      description: "4 L",
      price: 2.27,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/760/676/681131760676.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 42,
      name: " Nutella Hazelnut Chocolate Spread",
      description: "725g Jar",
      price: 6.67,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/956/598/956598.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 43,
      name: "Great Value Sweetened Condensed Milk",
      description: "300 mL",
      price: 1.67,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/973/617/6000197973617.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 44,
      name: "Terra Delyssa Tunisian Extra Virgin Olive Oil",
      description: "1 L",
      price: 9.97,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/903/627/999999-6191509903627.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 45,
      name: "Heinz Alphaghetti",
      description: "398mL",
      price: 1.97,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/_96/717/96717.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 46,
      name: "Hellmann's Real Mayonnaise",
      description: "398mL",
      price: 4.47,
      type: "pantry",
      url: "https://i5.walmartimages.ca/images/Thumbnails/676/806/6000196676806.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
  ],
  Bakery: [
    {
      id: 47,
      name: " Whole Grains Double Flax Bread",
      description: "600 g",
      price: 2.97,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/243/615/6000200243615.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 48,
      name: " Whole Grains Multigrain Bread",
      description: "600 g",
      price: 2.97,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/278/620/6000200278620.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 49,
      name: " Original White Bread",
      description: "570 g",
      price: 3.47,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/329/508/6000203329508.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 50,
      name: "Tuxedo Cake",
      description: "755 g",
      price: 12,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/261/137/6000203261137.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 51,
      name: "Chocolate Fudge Cake",
      description: "455 g",
      price: 5,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/549/471/6000202549471.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 56,
      name: "Vanilla Cupcakes",
      description: "206 g",
      price: 2.57,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/033/347/6000202033347.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 57,
      name: "Brownies",
      description: "680 g",
      price: 6,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/107/851/6000201107851.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 58,
      name: "Peanut Butter Cookies",
      description: "10 cookies, 390 g",
      price: 3.97,
      type: "bakery",
      url: "https://i5.walmartimages.ca/images/Thumbnails/374/499/6000203374499.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
  ],
  Frozen: [
    {
      id: 61,
      name: "Frozen Vegetables - Sweetlets Peas",
      description: "Green  Giant  Sweetlets Peas",
      price: 3.27,
      type: "frozen",
      url: "https://i5.walmartimages.ca/images/Thumbnails/423/274/999999-69052423274.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 62,
      name: "McCain® Crinkle Cut French Fries",
      description: "900g",
      price: 1.27,
      type: "frozen",
      url: "https://i5.walmartimages.com/asr/efef2822-bb08-4e46-aa6e-4d34e30eb477.77cf1b68ffdc5584ce9047b7824138bf.jpeg?odnHeight=180&odnWidth=180&odnBg=ffffff",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
    {
      id: 63,
      name: "Shrimp Ring",
      description: "454 g",
      price: 9.27,
      type: "frozen",
      url: "https://i5.walmartimages.ca/images/Thumbnails/029/188/6000203029188.jpg",
      ratings: 3,
      isFavorite: false,
      hasOffer: false,
      isAddedToCart: false,
      quantity: 0,
    },
  ],
};
